### ISSUE TITLE
Unable to compile on Windows for compute < 7.0

### ISSUE THREAD

**Issue by jllllll** [TimDettmers/bitsandbytes#434]
My best guess as to the reason is a limitation of the Windows Cuda Toolkit. Specifically, these are the errors that I get:

Cuda 11.6:
`fatal error C1189: #error:  "CUDA synchronization primitives are only supported for sm_70 and up."`

Cuda 12.1:
`fatal error C1189: #error:  "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."`
