### ISSUE TITLE
huggingface push_to_hub not working with bitsandbytes  0.39.1

### ISSUE THREAD

**Issue by bsabri** [TimDettmers/bitsandbytes#556]
Models loaded in load_in_8bit=True cannot be pushed to HF hub.
I get errors like:
AttributeError: 'str' object has no attribute 'numel' 

Whereas load_in_4bit=True pushing works
rolling back to 0.38 solved the problem.

**Comment by TimDettmers** [comment]
How about version 0.40.0.post4. Does it work with that?

**Comment by pvcastro** [comment]
@TimDettmers it's not working in 0.42 neither, just got the same issue
