### ISSUE TITLE
No support for SM_52 in bitsandbytes? Failed build process for synchronization functionality for Maxwell arch.

### ISSUE THREAD

**Issue by phalexo** [TimDettmers/bitsandbytes#451]
The Makefile lists Maxwell architecture as a possible target, but see below....

In file included from /usr/local/cuda-11.8/include/cuda/barrier:10,
                 from /usr/local/cuda-11.8/include/cuda/pipeline:57,
                 from /home/developer/bitsandbytes/csrc/kernels.cu:20:
/usr/local/cuda-11.8/include/cuda/std/barrier:11:4: error: #error "CUDA synchronization primitives are only supported for sm_70 and up."
   11 | #  error "CUDA synchronization primitives are only supported for sm_70 and up."
      |    ^~~~~
In file included from /usr/local/cuda-11.8/include/cuda/std/detail/libcxx/include/atomic:688,
                 from /usr/local/cuda-11.8/include/cuda/std/atomic:57,
                 from /usr/local/cuda-11.8/include/cuda/std/barrier:17,
                 from /usr/local/cuda-11.8/include/cuda/barrier:10,
                 from /usr/local/cuda-11.8/include/cuda/pipeline:57,
                 from /home/developer/bitsandbytes/csrc/kernels.cu:20:
/usr/local/cuda-11.8/include/cuda/std/detail/libcxx/include/support/atomic/atomic_cuda.h:11:4: error: #error "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."
   11 | #  error "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."
      |    ^~~~~
make: *** [Makefile:70: cuda11x_nomatmul] Error 1

**Comment by TimDettmers** [comment]
This is a duplicate of #477. But your issue actually highlights the main problem: There is no support for prefetching in 5.2 (it is not Windows related). As such, the functionality breaks support for Maxwell GPUs.

This means I have to decide to remove 5.2 support or include complicated code to ensure you can compile with SM 5.2.

**Comment by TimDettmers** [comment]
This has been fixed and pushed to pip. Memory problems might remain, but these are Windows-specific and there is nothing I can do about that. Thank you, this was an important bugfix.
